version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ...
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - java -jar target\awsdemo-0.0.1-SNAPSHOT.jar
