version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ...
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - mv target/awsdemo-0.0.1-SNAPSHOT.jar awsdemo-0.0.1-SNAPSHOT.jar
  post_build:
    commands:
      - echo Build completed on `date`
